language: go

go:
- 1.9

script: make release

deploy:
  provider: releases
  api_key:
    secure: PlsWtt7ZTXidanmSrrD08TsnCbYg9jdssZk7JKhEhN+pD9ZkT/cEDt047ATP65NIm60xjn9J9sWwPUr70ecBcViMPlDCxuMsd88f0kNtRbWzR45RBqzE8HEAE5mmw2VYzt7dZYXMDgV6I1Rl1ew9GQi0wQkhmIlkOTMlIF1gMztEDs8m2b3kz2eE1GGLzKomvhpwkefgZfeg5APwkLD/3BvOW9yDXeUNA4c+zL/r2+uf+XZFdYs05ebVWqlogswT63LP60rxZhnoNT4Daym/i9SjrS0cmjChMSRT0tsxi+o9sNoEwJmhMmi38I0IBhXv7xqCs/qdd1guyE8qp14kgZEzT42UbB+UG5GSU+HQmiPGcm1GpCmt/QD3y1qb6aIOX+XHsyF0x4DhQxfNmpV+TrbKhTEOhrA6IW4CtEx9WC+B5+K8bu0ermRUsY75lcw8Ah8Ab3C1uF/jbKx2G3KV5mCQ3GXfJRQ94in8dQUL5mKc5UzlC9xqfKBvIvAy7JDTrLAwDjWkxdaGo+v/ldhyYYfblqVNA89YM5998k6Oni0KEP3XvMjVP83ZlYWyfaVELHXnzNOuhxxHAk+YKLaU050t+Kayh7IvISTEBQCgAmsGRqOsbbHuWJ1fglIZR8w9hGs7w4mOcqqz+IoudGBikr5HRG6t388rRXimjEWB6V4=
  file_glob: true
  file: releases/*
  skip_cleanup: true
  on:
    tags: true

